- requirements.txt
Reverts noman-land/transcript.fish#10
> Revert "Bump urllib3 from 2.0.2 to 2.0.3"

- .gitignore
- data/nosuchfish.db
- package-lock.json
- package.json
- src/App.tsx
- src/Episodes.tsx
- src/ErrorBoundary.tsx
- src/convert.py
- src/convert.ts
- src/dbHooks.tsx
Get basic database connection and querying set up and fetch and show episodes.
Currently living at `/alpha`.
> feat: Display episodes

- src/App.tsx
- src/Episodes.tsx
- src/dbHooks.tsx
> feat: Add more episode info

- src/App.tsx
- src/Episodes.tsx
- src/dbHooks.tsx
Reverts noman-land/transcript.fish#16
> Revert "feat: Add more episode info"

- src/App.tsx
- src/Episodes.tsx
- src/dbHooks.tsx
Reverts noman-land/transcript.fish#17
> Revert "Revert "feat: Add more episode info""

- package-lock.json
- package.json
- src/EpisodesSearch.tsx
Trying to get rid of some search jank on mobile.
> Throttle search to 100ms

- .gitattributes
> chore: Remove LFS attributes

- .gitignore
- src/fetch.py
> chore: Some updates

- package-lock.json
> chore: Update deps

- public/fonts/LICENSE
Thank you to the author.
https://github.com/ctrlcctrlv/TT2020
> chore: Add font license

- README.md
- public/db/config.json
- src/dbHooks.tsx
Forgot to do this after adding episode 488 (#60).
https://www.sqlite.org/lang_vacuum.html
> chore: Vacuum

- .gitignore
- src/convert.py
- src/database.py
- src/fetch.py
- src/utils.py
> chore: Download images

- src/database.py
> fix(sql): Use proper field for ON CONFLICT

- src/database.py
Forgot to use the `excluded` keyword. TIL.
> fix(sql): Fix upsert

- src/js/EpisodesSearch.tsx
- src/js/FilterBar.tsx
- src/js/index.css
- src/js/types.ts
> feat: Add filters

- src/js/EpisodeRow.tsx
- src/js/EpisodeSummaryCell.tsx
- src/js/HostIcon.tsx
- src/js/types.ts
> feat: Add icons for hosts

- src/js/database.ts
This produces more accurate results.
> feath: Do exact match search

- package-lock.json
- package.json
- src/js/EmptyState.tsx
- src/js/EpisodeRow.tsx
- src/js/EpisodesSearch.tsx
- src/js/EpisodesTable.tsx
- src/js/FilterBar.tsx
- src/js/HostIcon.tsx
- src/js/Hosts.tsx
- src/js/Paginator.tsx
- src/js/SearchBar.tsx
- src/js/Spinner.tsx
- src/js/Total.tsx
- src/js/constants.ts
- src/js/database.ts
- src/js/dbHooks.tsx
- src/js/index.css
- src/js/styleUtils.ts
- src/js/types.ts
- src/js/utils.ts
> feat: Add presenter filters

- src/js/EpisodeRow.tsx
- src/js/EpisodeSummaryCell.tsx
- src/js/EpisodeTranscriptCell.tsx
- src/js/TimePrefixedWord.tsx
- src/js/constants.ts
- src/js/transcriptHooks.tsx
> feat: Highlight currently spoken sentence

- src/js/EmptyState.tsx
- src/js/EpisodeSearchFallback.tsx
- src/js/HostIcon.tsx
- src/js/Hosts.tsx
- src/js/Paginator.tsx
- src/js/SearchBar.tsx
- src/js/Separator.tsx
- src/js/Spinner.tsx
- src/js/Tags.tsx
- src/js/Total.tsx
- src/js/UnderConstructionBanner.tsx
Suddenly there were import and types problems.
> fix: Fix styled components errors

- README.md
- src/js/utils.ts
- src/python/convert.py
- src/python/fetch.py
- src/python/utils.py
I've been trying to set this up locally, here are a few fixes for issues I encountered.
Webapp CORS issues
- Added 127.0.0.1 as a hostname comparison in utils, though there still might be some exceptions to the rule (0.0.0.0?) Maybe a NODE_ENV or --mode flag might be more appropriate
Convert:
- Added a util function to create the images/episodes/ and audio/ folders, as they are in .gitignore it causes an issue on first time conversion since the paths do not yet exist
- Add README information about running the convert command and changing model type
> fix: Create local folders if they don't exist

- db/migrations.sql
- src/python/database.py
Remove events column from venues table and add a whole table for it.
Not every performance at a particular venue wasn't always accompanied by the same event.
> feat: Add events table

- src/js/EpisodeRow.tsx
- src/js/EpisodesSearch.tsx
- src/js/EpisodesTable.tsx
- src/js/Total.tsx
- src/js/types.ts
https://github.com/noman-land/transcript.fish/assets/27938023/49a93f55-77e5-4281-bb70-e891d129e474
> feat: Add expand all button

- package-lock.json
Reverts noman-land/transcript.fish#243
> Revert "chore: Update deps"

- src/js/EpisodesSearch.tsx
- src/js/Total.tsx
- src/js/filters/FilterBar.tsx
- src/js/filters/FilterSection.tsx
- src/js/filters/FiltersToggle.tsx
> feat: Collapsable filters

- src/js/filters/FiltersContext.tsx
- src/js/filters/FiltersToggle.tsx
> feat: Show number of filters altered in parentheses

- src/js/EpisodeSummaryCell.tsx
- src/js/EpisodesSearch.tsx
- src/js/database.ts
- src/js/dbHooks.tsx
- src/js/filters/DropdownMultiselect.tsx
- src/js/filters/FilterBar.tsx
- src/js/filters/FiltersContext.tsx
- src/js/filters/PresenterFilters.tsx
- src/js/filters/VenueFilters.tsx
- src/js/filters/filterUtils.ts
- src/js/types.ts
- src/js/utils.ts
https://github.com/noman-land/transcript.fish/assets/27938023/7752d95d-62c0-425c-9e82-8a8c0b754b0d
> feat(filters): Venue filter

- src/python/whisper.py
> feat: Add progress logs to transcription script

- src/python/classes.py
- src/python/convert.py
- src/python/database.py
- src/python/fetch.py
- src/python/utils.py
- src/python/whisper.py
- better typing
- variable name tweaks
- break out some functions
- show progress during transcription
> chore: Tidy up and enhancements

- src/python/convert.py
- src/python/database.py
Bug introduced in https://github.com/noman-land/transcript.fish/pull/285.
> fix: Handle new episodes

- src/python/utils.py
> chore: Show progress on same line

- db/migrations.sql
- src/python/classes.py
- src/python/database.py
- src/python/fetch.py
- src/python/sql.py
- src/python/utils.py
Currently the convert script crashes when being run for the first time after cloning this repo. This is because it's missing asset folders and the database initialization. This PR adds those things.
> fix: Make first run better

- src/js/EpisodeRow.tsx
- src/js/database/DatabaseProvider.tsx
This was causing every row to show whichever transcript was fetched first.
> fix: Each row should fetches its own transcript

- src/js/EpisodeTranscriptCell.tsx
- src/js/Occurrences.tsx
- src/js/index.css
- src/js/utils.ts
Thanks to `@Flattened Spectre` on Discord for the idea.
> feat: Add number of search term occurrences above transcript

- requirements.txt
- src/python/database.py
- src/python/sql.py
- src/python/whisper.py
This cuts the transcription time from over an hour to about ten minutes!
> chore: Update faster-whisper version and use better model
